package String;

/*
    You are given two strings s and t.
    String t is generated by random shuffling string s and then add one more letter at a random position.
    Return the letter that was added to t.
 */
public class FindTheDifference {

    public static char findTheDifference(String s, String t) {
        int xor = 0;

        for (char c : s.toCharArray()) {
            xor ^= c;
        }

        for (char c : t.toCharArray()) {
            xor ^= c;
        }

        return (char) xor;
    }

    public static void main(String[] args) {
        String s = "abcd";
        String t = "abcde";
        char output = findTheDifference(s, t);
        System.out.println("Output : " + output);
    }

}
